name: Behance Posts

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest my latest posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 5
          comment_tag_name: "BEHANCE"
          feed_list: "https://www.behance.net/feeds/user?username=amirzenoozi"
          commit_message: ":memo: update behance project list"
